### PR TITLE
Add linux firmware package for all other distro

### PR DESCRIPTION
**Pull request by vireakvibol**

### CODE REVIEW

**Comment by vireakvibol** [comment]
I'm not really sure yet if debian ubuntu and fedora really need linux-firmware but this should add otherwise can be reverted later on.

**Comment by i2** [comment]
I will leave this open until users report similar `stuck at starting version` issues. I am a bit hesitant for non-free package on Debian.

**Comment by vireakvibol** [comment]
Seem like **archlinux, endeavouros, ubuntu, fedora** use the same package name **linux-firmware**
Only debian use package name **firmware-linux**
Not sure in **cachyos**

**Comment by i2** [comment]
CachyOS should be same as Arch

**Comment by vireakvibol** [comment]
Alright! already double check on the package name. Only test on real distro is not yet perform.

**Review by i2 — APPROVED** [review]

**Pull request merged**
