### PR TITLE
AUR support implementation

### PR DESCRIPTION
**Pull request by CuBeRJAN**
I think it's stable now, I would still leave this PR here for a bit for more testing, but everything should be working perfectly!

### CODE REVIEW

**Comment by CuBeRJAN** [comment]
code has been cleaned up, more testing is all that's left

**Comment by CuBeRJAN** [comment]
Well, I lied, more testing wasn't the only thing left - more documentation had to be written too!

**Review by i2 — CHANGES_REQUESTED** [review]
There are changes needed to conform to AshOS:
1. Readme.md should clarify these sections are Arch Linux specific.
2. The modifications in astpk.py should be manually merged to ./src/distros/arch/ashpk.py
3. If there are any part of code that can be abstracted away and put in ashpk_core.py, that'd be preferred. We want to keep distro-specific ashpk.py files as small as possible (for easier translation to other distros)

**Comment by i2** [comment]
Things look good and it's time to close this PR. I have included it in #69.

**Pull request closed without merging**
